import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const examplesBasePath = path.join(__dirname, `../../public/assets/product_examples`);
const outputFilePath = path.join(__dirname, '../../public/productExamplesData.js');
const availableTypesFilePath = path.join(__dirname, '../../public/availableProductTypes.json');

const availableTypesByProduct = {};
const productExamplesData = {};

try {
    const productFolders = fs.readdirSync(examplesBasePath, { withFileTypes: true })
        .filter(dirent => dirent.isDirectory())
        .map(dirent => dirent.name);

    productFolders.forEach(productFolder => {
        const productPath = path.join(examplesBasePath, productFolder);
        const availableTypesForProduct = [];

        const typeFolders = fs.readdirSync(productPath, { withFileTypes: true })
            .filter(dirent => dirent.isDirectory())
            .map(dirent => dirent.name);

        typeFolders.forEach(type => {
            const typePath = path.join(productPath, type);
            if (fs.existsSync(typePath) && fs.statSync(typePath).isDirectory() && fs.readdirSync(typePath).length > 0) {
                const uppercaseType = type.toUpperCase();
                availableTypesForProduct.push(uppercaseType);

                const imageFiles = fs.readdirSync(typePath)
                    .filter(file => ['.jpg', '.jpeg', '.png', '.gif', '.svg', '.webp'].includes(path.extname(file).toLowerCase()));

                if (!productExamplesData[uppercaseType]) {
                    productExamplesData[uppercaseType] = [];
                }
                imageFiles.forEach(file => {
                    productExamplesData[uppercaseType].push({
                        src: `product_examples/${productFolder}/${type}/${file}`,
                        productName: productFolder,
                    });
                });
            }
        });

        if (availableTypesForProduct.length > 0) {
            availableTypesByProduct[productFolder] = availableTypesForProduct;
        }
    });

    // Create the output JS module content for product examples data
    const outputContent = `// This file is auto-generated by scripts/generateProductExamples.js
export const productExamplesData = ${JSON.stringify(productExamplesData, null, 2)};
`;
    fs.writeFileSync(outputFilePath, outputContent, 'utf8');
    console.log(`Successfully generated product examples data at ${outputFilePath}`);

    // Create the JSON file for available product types per product
    fs.writeFileSync(availableTypesFilePath, JSON.stringify(availableTypesByProduct, null, 2));
    console.log(`Successfully generated available product types per product at ${availableTypesFilePath}`);

} catch (error) {
    console.error('Error generating data:', error);
    process.exit(1);
}
