// This file is auto-generated by scripts/generateProductExamples.js
export const productExamplesData = {
  "FLAMED": [],
  "CLADDING": [
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/CLADDING/RENAISSANCE STONES BEIGE MARBLE 1 copy.webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/CLADDING/RENAISSANCE STONES BEIGE MARBLE 2 copy(1).webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/CLADDING/RENAISSANCE STONES BEIGE MARBLE 2 copy.webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/BWH-B WHITE/CLADDING/1 copy.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/BWH-B WHITE/CLADDING/RENAISSANCE STONES B.WHITE  1.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/BWH-B WHITE/CLADDING/RENAISSANCE STONES B.WHITE 2.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/BWH-B WHITE/CLADDING/RENAISSANCE STONES B.WHITE 3.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/CVN-C VENATO/CLADDING/RENAISSANCE STONES C.VENATO 1.webp",
      "productName": "CVN-C VENATO"
    },
    {
      "src": "./product_examples/CVN-C VENATO/CLADDING/RENAISSANCE STONES C.VENATO 2.webp",
      "productName": "CVN-C VENATO"
    },
    {
      "src": "./product_examples/CVN-C VENATO/CLADDING/RENAISSANCE STONES C.VENATO 3.webp",
      "productName": "CVN-C VENATO"
    },
    {
      "src": "./product_examples/CVN-C VENATO/CLADDING/RENAISSANCE STONES C.VENATO 4.webp",
      "productName": "CVN-C VENATO"
    },
    {
      "src": "./product_examples/CVN-C VENATO/CLADDING/RENAISSANCE STONES C.VENATO 5.webp",
      "productName": "CVN-C VENATO"
    },
    {
      "src": "./product_examples/CVN-C VENATO/CLADDING/RENAISSANCE STONES C.VENATO 6.webp",
      "productName": "CVN-C VENATO"
    },
    {
      "src": "./product_examples/CVN-C VENATO/CLADDING/RENAISSANCE STONES C.VENATO 7.webp",
      "productName": "CVN-C VENATO"
    }
  ],
  "FLOOR": [
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/FLOOR/RENAISSANCE STONE BEIGE MARBLE 5.webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/FLOOR/RENAISSANCE STONE BEIGE MARBLE 6.webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/M BLACK/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  1.webp",
      "productName": "M BLACK"
    },
    {
      "src": "./product_examples/M BLACK/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  2.webp",
      "productName": "M BLACK"
    },
    {
      "src": "./product_examples/M BLACK/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  3.webp",
      "productName": "M BLACK"
    },
    {
      "src": "./product_examples/M BLACK/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  4.webp",
      "productName": "M BLACK"
    },
    {
      "src": "./product_examples/M BLACK/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  5.webp",
      "productName": "M BLACK"
    },
    {
      "src": "./product_examples/M BLACK/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  6.webp",
      "productName": "M BLACK"
    },
    {
      "src": "./product_examples/M BLACK/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  7.webp",
      "productName": "M BLACK"
    },
    {
      "src": "./product_examples/M BLACK/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  8.webp",
      "productName": "M BLACK"
    },
    {
      "src": "./product_examples/M BLACK/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  9.webp",
      "productName": "M BLACK"
    },
    {
      "src": "./product_examples/M BLACK/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK 10.webp",
      "productName": "M BLACK"
    },
    {
      "src": "./product_examples/PLW-P WHITE/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  6.webp",
      "productName": "PLW-P WHITE"
    },
    {
      "src": "./product_examples/PLW-P WHITE/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  7.webp",
      "productName": "PLW-P WHITE"
    },
    {
      "src": "./product_examples/PLW-P WHITE/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  8.webp",
      "productName": "PLW-P WHITE"
    },
    {
      "src": "./product_examples/PLW-P WHITE/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK  9.webp",
      "productName": "PLW-P WHITE"
    },
    {
      "src": "./product_examples/PLW-P WHITE/FLOOR/RENAISSANCE STONES P.WHITE AND M.BLACK 10.webp",
      "productName": "PLW-P WHITE"
    },
    {
      "src": "./product_examples/SBL-S BLUE/FLOOR/RENAISSANCE STONES B.WHITE AND S.BLUE 1.webp",
      "productName": "SBL-S BLUE"
    },
    {
      "src": "./product_examples/SBL-S BLUE/FLOOR/RENAISSANCE STONES B.WHITE AND S.BLUE 2.webp",
      "productName": "SBL-S BLUE"
    },
    {
      "src": "./product_examples/SBL-S BLUE/FLOOR/RENAISSANCE STONES B.WHITE AND S.BLUE 3.webp",
      "productName": "SBL-S BLUE"
    },
    {
      "src": "./product_examples/SBL-S BLUE/FLOOR/RENAISSANCE STONES B.WHITE AND S.BLUE 4.webp",
      "productName": "SBL-S BLUE"
    }
  ],
  "STAIR": [
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/STAIR/RENAISSANCE STONE BEIGE MARBLE 1.webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/STAIR/RENAISSANCE STONE BEIGE MARBLE 2.webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/STAIR/RENAISSANCE STONE BEIGE MARBLE 4.webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/STAIR/RENAISSANCE STONES BEIGE MARBLE 1.webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/STAIR/RENAISSANCE STONES BEIGE MARBLE 2.webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/BWH-B WHITE/STAIR/RENAISSANCE STONES B WHITE 1  copy.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/BWH-B WHITE/STAIR/RENAISSANCE STONES B WHITE 2  copy.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/BWH-B WHITE/STAIR/RENAISSANCE STONES B WHITE 3  copy.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/BWH-B WHITE/STAIR/RENAISSANCE STONES B WHITE 4  copy.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/COB-C BLACK/STAIR/RENAISSANCE STONES COB 1.webp",
      "productName": "COB-C BLACK"
    },
    {
      "src": "./product_examples/COB-C BLACK/STAIR/RENAISSANCE STONES COB 2.webp",
      "productName": "COB-C BLACK"
    },
    {
      "src": "./product_examples/COB-C BLACK/STAIR/RENAISSANCE STONES COB 3.webp",
      "productName": "COB-C BLACK"
    },
    {
      "src": "./product_examples/COB-C BLACK/STAIR/RENAISSANCE STONES COB 4.webp",
      "productName": "COB-C BLACK"
    },
    {
      "src": "./product_examples/COB-C BLACK/STAIR/RENAISSANCE STONES COB 5.webp",
      "productName": "COB-C BLACK"
    },
    {
      "src": "./product_examples/FBL-F BLACK/STAIR/RENAISSANCE STONES F.BLACK 2.webp",
      "productName": "FBL-F BLACK"
    },
    {
      "src": "./product_examples/FBL-F BLACK/STAIR/RENAISSANCE STONES F.BLACK 4.webp",
      "productName": "FBL-F BLACK"
    },
    {
      "src": "./product_examples/FBL-F BLACK/STAIR/RENAISSANCE STONES F.BLACK 5.webp",
      "productName": "FBL-F BLACK"
    },
    {
      "src": "./product_examples/FBL-F BLACK/STAIR/RENAISSANCE STONES F.BLACK 6.webp",
      "productName": "FBL-F BLACK"
    },
    {
      "src": "./product_examples/FBL-F BLACK/STAIR/RENAISSANCE STONES F.BLACK 7.webp",
      "productName": "FBL-F BLACK"
    },
    {
      "src": "./product_examples/LBU-L BLUE/STAIR/RENAISSANCE STONES L.BLUE 1.webp",
      "productName": "LBU-L BLUE"
    },
    {
      "src": "./product_examples/LBU-L BLUE/STAIR/RENAISSANCE STONES L.BLUE 10.webp",
      "productName": "LBU-L BLUE"
    },
    {
      "src": "./product_examples/LBU-L BLUE/STAIR/RENAISSANCE STONES L.BLUE 2.webp",
      "productName": "LBU-L BLUE"
    },
    {
      "src": "./product_examples/LBU-L BLUE/STAIR/RENAISSANCE STONES L.BLUE 3.webp",
      "productName": "LBU-L BLUE"
    },
    {
      "src": "./product_examples/LBU-L BLUE/STAIR/RENAISSANCE STONES L.BLUE 5.webp",
      "productName": "LBU-L BLUE"
    },
    {
      "src": "./product_examples/LBU-L BLUE/STAIR/RENAISSANCE STONES L.BLUE 6.webp",
      "productName": "LBU-L BLUE"
    },
    {
      "src": "./product_examples/LBU-L BLUE/STAIR/RENAISSANCE STONES L.BLUE 7.webp",
      "productName": "LBU-L BLUE"
    },
    {
      "src": "./product_examples/PLW-P WHITE/STAIR/RENAISSANCE STONES P.WHITE 1.webp",
      "productName": "PLW-P WHITE"
    },
    {
      "src": "./product_examples/RIV-RIVER WHITE/STAIR/RENAISSANCE STONES RIV 1.webp",
      "productName": "RIV-RIVER WHITE"
    },
    {
      "src": "./product_examples/RIV-RIVER WHITE/STAIR/RENAISSANCE STONES RIV 2.webp",
      "productName": "RIV-RIVER WHITE"
    },
    {
      "src": "./product_examples/RIV-RIVER WHITE/STAIR/RENAISSANCE STONES RIV 3.webp",
      "productName": "RIV-RIVER WHITE"
    },
    {
      "src": "./product_examples/RIV-RIVER WHITE/STAIR/RENAISSANCE STONES RIV 4.webp",
      "productName": "RIV-RIVER WHITE"
    },
    {
      "src": "./product_examples/RIV-RIVER WHITE/STAIR/RENAISSANCE STONES RIV 5.webp",
      "productName": "RIV-RIVER WHITE"
    },
    {
      "src": "./product_examples/RIV-RIVER WHITE/STAIR/RENAISSANCE STONES RIV 6.webp",
      "productName": "RIV-RIVER WHITE"
    },
    {
      "src": "./product_examples/RIV-RIVER WHITE/STAIR/RENAISSANCE STONES RIV 7.webp",
      "productName": "RIV-RIVER WHITE"
    },
    {
      "src": "./product_examples/VBL-V BLUE/STAIR/RENAISSANCE STONES V.BLUE 1 (1).webp",
      "productName": "VBL-V BLUE"
    },
    {
      "src": "./product_examples/VBL-V BLUE/STAIR/RENAISSANCE STONES V.BLUE 1.webp",
      "productName": "VBL-V BLUE"
    },
    {
      "src": "./product_examples/VBL-V BLUE/STAIR/RENAISSANCE STONES V.BLUE 2 (1).webp",
      "productName": "VBL-V BLUE"
    },
    {
      "src": "./product_examples/VBL-V BLUE/STAIR/RENAISSANCE STONES V.BLUE 2.webp",
      "productName": "VBL-V BLUE"
    },
    {
      "src": "./product_examples/VBL-V BLUE/STAIR/RENAISSANCE STONES V.BLUE 3 (1).webp",
      "productName": "VBL-V BLUE"
    },
    {
      "src": "./product_examples/VBL-V BLUE/STAIR/RENAISSANCE STONES V.BLUE 3.webp",
      "productName": "VBL-V BLUE"
    },
    {
      "src": "./product_examples/VBL-V BLUE/STAIR/RENAISSANCE STONES V.BLUE 4.webp",
      "productName": "VBL-V BLUE"
    }
  ],
  "TABLE TOP": [
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/TABLE TOP/RENAISSANCE 14.webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/BGM-BEIGE MARBLE/TABLE TOP/RENAISSANCE 15.webp",
      "productName": "BGM-BEIGE MARBLE"
    },
    {
      "src": "./product_examples/RIV-RIVER WHITE/TABLE TOP/RENAISSANCE STONES RIV 1.webp",
      "productName": "RIV-RIVER WHITE"
    },
    {
      "src": "./product_examples/RIV-RIVER WHITE/TABLE TOP/RENAISSANCE STONES RIV 2.webp",
      "productName": "RIV-RIVER WHITE"
    },
    {
      "src": "./product_examples/RIV-RIVER WHITE/TABLE TOP/RENAISSANCE STONES RIV 3.webp",
      "productName": "RIV-RIVER WHITE"
    },
    {
      "src": "./product_examples/RIV-RIVER WHITE/TABLE TOP/RENAISSANCE STONES RIV 4.webp",
      "productName": "RIV-RIVER WHITE"
    }
  ],
  "KITCHEN COUNTERTOP": [
    {
      "src": "./product_examples/BGX-B GALAXY/KITCHEN COUNTERTOP/RENAAISSANCE STONES B.GALAXY 1.webp",
      "productName": "BGX-B GALAXY"
    },
    {
      "src": "./product_examples/BGX-B GALAXY/KITCHEN COUNTERTOP/RENAAISSANCE STONES B.GALAXY 2.webp",
      "productName": "BGX-B GALAXY"
    },
    {
      "src": "./product_examples/BGX-B GALAXY/KITCHEN COUNTERTOP/RENAAISSANCE STONES B.GALAXY 3.webp",
      "productName": "BGX-B GALAXY"
    },
    {
      "src": "./product_examples/BGX-B GALAXY/KITCHEN COUNTERTOP/RENAISSANCE STONES B.GALAXY 1.webp",
      "productName": "BGX-B GALAXY"
    },
    {
      "src": "./product_examples/BGX-B GALAXY/KITCHEN COUNTERTOP/RENAISSANCE STONES B.GALAXY 2.webp",
      "productName": "BGX-B GALAXY"
    },
    {
      "src": "./product_examples/BWH-B WHITE/KITCHEN COUNTERTOP/RENAISSANCE STONE B.WHITE 10.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/BWH-B WHITE/KITCHEN COUNTERTOP/RENAISSANCE STONE B.WHITE 14.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/BWH-B WHITE/KITCHEN COUNTERTOP/RENAISSANCE STONE B.WHITE 6.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/BWH-B WHITE/KITCHEN COUNTERTOP/RENAISSANCE STONE B.WHITE 8.webp",
      "productName": "BWH-B WHITE"
    },
    {
      "src": "./product_examples/CVN-C VENATO/KITCHEN COUNTERTOP/RENAISSANCE STONE B.WHITE 10.webp",
      "productName": "CVN-C VENATO"
    },
    {
      "src": "./product_examples/CVN-C VENATO/KITCHEN COUNTERTOP/RENAISSANCE STONE B.WHITE 12.webp",
      "productName": "CVN-C VENATO"
    },
    {
      "src": "./product_examples/CVN-C VENATO/KITCHEN COUNTERTOP/RENAISSANCE STONE B.WHITE 14.webp",
      "productName": "CVN-C VENATO"
    },
    {
      "src": "./product_examples/FBR-F BROWN/KITCHEN COUNTERTOP/RENAISSANCE STONES F.BROWN 1.webp",
      "productName": "FBR-F BROWN"
    },
    {
      "src": "./product_examples/FBR-F BROWN/KITCHEN COUNTERTOP/RENAISSANCE STONES F.BROWN 2.webp",
      "productName": "FBR-F BROWN"
    },
    {
      "src": "./product_examples/HBR-H BROWN/KITCHEN COUNTERTOP/RENAISSANCE STONES H.BROWN 1.webp",
      "productName": "HBR-H BROWN"
    },
    {
      "src": "./product_examples/HBR-H BROWN/KITCHEN COUNTERTOP/RENAISSANCE STONES H.BROWN 2.webp",
      "productName": "HBR-H BROWN"
    },
    {
      "src": "./product_examples/HBR-H BROWN/KITCHEN COUNTERTOP/RENAISSANCE STONES H.BROWN 3.webp",
      "productName": "HBR-H BROWN"
    },
    {
      "src": "./product_examples/HBR-H BROWN/KITCHEN COUNTERTOP/RENAISSANCE STONES H.BROWN 4.webp",
      "productName": "HBR-H BROWN"
    },
    {
      "src": "./product_examples/SGD-S GOLD/KITCHEN COUNTERTOP/RENAISSANCE STONES S.GOLD 1.webp",
      "productName": "SGD-S GOLD"
    },
    {
      "src": "./product_examples/SGD-S GOLD/KITCHEN COUNTERTOP/RENAISSANCE STONES S.GOLD 3.webp",
      "productName": "SGD-S GOLD"
    }
  ],
  "TOMBSTONE": [
    {
      "src": "./product_examples/BGX-B GALAXY/TOMBSTONE/RENAISSANCE STONE S.GOLD & B.GALAXY 1.webp",
      "productName": "BGX-B GALAXY"
    },
    {
      "src": "./product_examples/IMR-I RED/TOMBSTONE/RENAISSANCE STONE I.RED A.webp",
      "productName": "IMR-I RED"
    },
    {
      "src": "./product_examples/IMR-I RED/TOMBSTONE/RENAISSANCE STONE I.RED B.webp",
      "productName": "IMR-I RED"
    },
    {
      "src": "./product_examples/IMR-I RED/TOMBSTONE/RENAISSANCE STONE I.RED C.webp",
      "productName": "IMR-I RED"
    },
    {
      "src": "./product_examples/IMR-I RED/TOMBSTONE/RENAISSANCE STONE I.RED D.webp",
      "productName": "IMR-I RED"
    },
    {
      "src": "./product_examples/IMR-I RED/TOMBSTONE/RENAISSANCE STONE I.RED E.webp",
      "productName": "IMR-I RED"
    },
    {
      "src": "./product_examples/IMR-I RED/TOMBSTONE/RENAISSANCE STONE I.RED F.webp",
      "productName": "IMR-I RED"
    },
    {
      "src": "./product_examples/SGD-S GOLD/TOMBSTONE/RENAISSANCE STONE S.GOLD 5.webp",
      "productName": "SGD-S GOLD"
    },
    {
      "src": "./product_examples/SGD-S GOLD/TOMBSTONE/RENAISSANCE STONE S.GOLD 6.webp",
      "productName": "SGD-S GOLD"
    },
    {
      "src": "./product_examples/SGD-S GOLD/TOMBSTONE/RENAISSANCE STONE S.GOLD 7.webp",
      "productName": "SGD-S GOLD"
    }
  ],
  "COPPING ": [
    {
      "src": "./product_examples/CBG-C GREY/COPPING /RENAISSANCE STONES C.GREY 3.webp",
      "productName": "CBG-C GREY"
    },
    {
      "src": "./product_examples/CBG-C GREY/COPPING /RENAISSANCE STONES C.GREY 4.webp",
      "productName": "CBG-C GREY"
    },
    {
      "src": "./product_examples/CBG-C GREY/COPPING /RENAISSANCE STONES C.GREY 5.webp",
      "productName": "CBG-C GREY"
    }
  ],
  "WINDOW SILL": [
    {
      "src": "./product_examples/CBG-C GREY/WINDOW SILL/RENAISSANCE STONES C.GREY 1.webp",
      "productName": "CBG-C GREY"
    },
    {
      "src": "./product_examples/CBG-C GREY/WINDOW SILL/RENAISSANCE STONES C.GREY 2.webp",
      "productName": "CBG-C GREY"
    }
  ],
  "BATHROOM SINK": [
    {
      "src": "./product_examples/FBL-F BLACK/BATHROOM SINK/RENAISSANCE STONES F BLACK 1.webp",
      "productName": "FBL-F BLACK"
    },
    {
      "src": "./product_examples/FBL-F BLACK/BATHROOM SINK/RENAISSANCE STONES F BLACK 2.webp",
      "productName": "FBL-F BLACK"
    }
  ],
  "CLADDING ": [
    {
      "src": "./product_examples/LBU-L BLUE/CLADDING /RENAISSANCE STONES l.BLUE 1.webp",
      "productName": "LBU-L BLUE"
    },
    {
      "src": "./product_examples/LBU-L BLUE/CLADDING /RENAISSANCE STONES l.BLUE 2.webp",
      "productName": "LBU-L BLUE"
    }
  ],
  "DOOR SILL": [
    {
      "src": "./product_examples/VGR-V GREEN/DOOR SILL/RENAISSANCE STONES V.GREEN 5.webp",
      "productName": "VGR-V GREEN"
    },
    {
      "src": "./product_examples/VGR-V GREEN/DOOR SILL/RENAISSANCE STONES V.GREEN 6.webp",
      "productName": "VGR-V GREEN"
    }
  ],
  "STAIRS": [
    {
      "src": "./product_examples/VGR-V GREEN/STAIRS/RENAISSANCE STONES V.GREEN 1.webp",
      "productName": "VGR-V GREEN"
    },
    {
      "src": "./product_examples/VGR-V GREEN/STAIRS/RENAISSANCE STONES V.GREEN 2.webp",
      "productName": "VGR-V GREEN"
    },
    {
      "src": "./product_examples/VGR-V GREEN/STAIRS/RENAISSANCE STONES V.GREEN 3.webp",
      "productName": "VGR-V GREEN"
    },
    {
      "src": "./product_examples/VGR-V GREEN/STAIRS/RENAISSANCE STONES V.GREEN 4.webp",
      "productName": "VGR-V GREEN"
    }
  ]
};
